/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.endicott.csc.jframes;

import edu.endicott.csc.client.Client;
import edu.endicott.csc.finalproject.Controller;
import edu.endicott.csc.finalproject.GameList;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cesar
 */
public class SearchWindow extends Window {
    private int searchPage = 0;
    
    /**
     * Creates new form SearchWindow
     */
    public SearchWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topOptionsBar1 = new edu.endicott.csc.forms.TopOptionsBar();
        sideBar1 = new edu.endicott.csc.forms.SideBar();
        searchResultPanel1 = new edu.endicott.csc.forms.SearchResultPanel();
        searchResultPanel2 = new edu.endicott.csc.forms.SearchResultPanel();
        searchResultPanel3 = new edu.endicott.csc.forms.SearchResultPanel();
        searchResultPanel4 = new edu.endicott.csc.forms.SearchResultPanel();
        searchResultPanel5 = new edu.endicott.csc.forms.SearchResultPanel();
        searchResultPanel6 = new edu.endicott.csc.forms.SearchResultPanel();
        btnGoLeft = new javax.swing.JButton();
        btnGoRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SteamDB App");

        searchResultPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultPanel1MouseClicked(evt);
            }
        });

        searchResultPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultPanel2MouseClicked(evt);
            }
        });

        searchResultPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultPanel3MouseClicked(evt);
            }
        });

        searchResultPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultPanel4MouseClicked(evt);
            }
        });

        searchResultPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultPanel5MouseClicked(evt);
            }
        });

        searchResultPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultPanel6MouseClicked(evt);
            }
        });

        btnGoLeft.setText("<-");
        btnGoLeft.setPreferredSize(new java.awt.Dimension(73, 73));
        btnGoLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLeftActionPerformed(evt);
            }
        });

        btnGoRight.setText("->");
        btnGoRight.setPreferredSize(new java.awt.Dimension(73, 73));
        btnGoRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topOptionsBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchResultPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchResultPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchResultPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchResultPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGoLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchResultPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchResultPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(btnGoRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topOptionsBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchResultPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchResultPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchResultPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGoRight, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGoLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(searchResultPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchResultPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchResultPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLeftActionPerformed
        if (searchPage > 0){
            this.searchPage--;
            
            try {
                updateSearchPanels();
            } catch (IOException ex) {
                Logger.getLogger(SearchWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (Controller.getController().searchResults.size() > (searchPage+1)*6){
                btnGoRight.setVisible(true);
                btnGoRight.setEnabled(true);
            }
            if (searchPage == 0) {
                btnGoLeft.setVisible(false);
                btnGoLeft.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnGoLeftActionPerformed

    private void btnGoRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoRightActionPerformed
        if (Controller.getController().searchResults.size() > (searchPage+1)*6){
            this.searchPage++;
            
            try {
                updateSearchPanels();
            } catch (IOException ex) {
                Logger.getLogger(SearchWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (searchPage > 0){
                btnGoLeft.setVisible(true);
                btnGoLeft.setEnabled(true);
            }
            if(Controller.getController().searchResults.size() <= (searchPage+1)*6) {
                btnGoRight.setVisible(false);
                btnGoRight.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnGoRightActionPerformed

    private void searchResultPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultPanel1MouseClicked
        try {
            Controller.getController().currentGameInfo =
                    Client.client.getGameInfo(Controller.getController()
                            .searchResults.get(6*this.searchPage).appid);
            Controller.getController().windows.get(Controller.getController()
            .currentWindow).goToPage(Controller.ENTRY_WINDOW);
        } catch (IOException ex) {
            Logger.getLogger(SearchWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchResultPanel1MouseClicked

    private void searchResultPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultPanel2MouseClicked
        try {
            Controller.getController().currentGameInfo =
                    Client.client.getGameInfo(Controller.getController()
                            .searchResults.get(6*this.searchPage+1).appid);
            Controller.getController().windows.get(Controller.getController()
            .currentWindow).goToPage(Controller.ENTRY_WINDOW);
        } catch (IOException ex) {
            Logger.getLogger(SearchWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchResultPanel2MouseClicked

    private void searchResultPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultPanel3MouseClicked
        try {
            Controller.getController().currentGameInfo =
                    Client.client.getGameInfo(Controller.getController()
                            .searchResults.get(6*this.searchPage+2).appid);
            Controller.getController().windows.get(Controller.getController()
            .currentWindow).goToPage(Controller.ENTRY_WINDOW);
        } catch (IOException ex) {
            Logger.getLogger(SearchWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchResultPanel3MouseClicked

    private void searchResultPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultPanel4MouseClicked
        try {
            Controller.getController().currentGameInfo =
                    Client.client.getGameInfo(Controller.getController()
                            .searchResults.get(6*this.searchPage+3).appid);
            Controller.getController().windows.get(Controller.getController()
            .currentWindow).goToPage(Controller.ENTRY_WINDOW);
        } catch (IOException ex) {
            Logger.getLogger(SearchWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchResultPanel4MouseClicked

    private void searchResultPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultPanel5MouseClicked
        try {
            Controller.getController().currentGameInfo =
                    Client.client.getGameInfo(Controller.getController()
                            .searchResults.get(6*this.searchPage+4).appid);
            Controller.getController().windows.get(Controller.getController()
            .currentWindow).goToPage(Controller.ENTRY_WINDOW);
        } catch (IOException ex) {
            Logger.getLogger(SearchWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchResultPanel5MouseClicked

    private void searchResultPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultPanel6MouseClicked
        try {
            Controller.getController().currentGameInfo =
                    Client.client.getGameInfo(Controller.getController()
                            .searchResults.get(6*this.searchPage+5).appid);
            Controller.getController().windows.get(Controller.getController()
            .currentWindow).goToPage(Controller.ENTRY_WINDOW);
        } catch (IOException ex) {
            Logger.getLogger(SearchWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchResultPanel6MouseClicked

    @Override
    public void setVisible(boolean b){
        if (!b) {
            this.searchPage = 0;
        }
        
        super.setVisible(b);
        topOptionsBar1.setUsername();
        btnGoLeft.setVisible(false);
        
        try {
            updateSearchPanels();
        } catch (IOException ex) {
            Logger.getLogger(SearchWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     *
     * @throws IOException
     */
    public void updateSearchPanels() throws IOException {
        ArrayList<GameList.AppList.Game> searchList = 
                Controller.getController().searchResults;
        
        searchResultPanel1.setResultTitle("");
        searchResultPanel2.setResultTitle("");
        searchResultPanel3.setResultTitle("");
        searchResultPanel4.setResultTitle("");
        searchResultPanel5.setResultTitle("");
        searchResultPanel6.setResultTitle("");
        
        searchResultPanel1.setResultImage(null);
        searchResultPanel2.setResultImage(null);
        searchResultPanel3.setResultImage(null);
        searchResultPanel4.setResultImage(null);
        searchResultPanel5.setResultImage(null);
        searchResultPanel6.setResultImage(null);
        
        searchResultPanel1.setResultTitle(
                Controller.getController().searchResults.get(6*searchPage).name);
        if (Client.client.getGameInfo(searchList.get(6*searchPage).appid) != null){
            searchResultPanel1.setResultImage(
                    new URL(Client.client.getGameInfo(
                            searchList.get(6*searchPage).appid).data.header_image));
        }
        if (6*searchPage+1 < Controller.getController().searchResults.size()) {
            searchResultPanel2.setResultTitle(
                    Controller.getController().searchResults.get(6*searchPage+1).name);
            if (Client.client.getGameInfo(searchList.get(6*searchPage+1).appid) != null){
            searchResultPanel2.setResultImage(
                    new URL(Client.client.getGameInfo(
                            searchList.get(6*searchPage+1).appid).data.header_image));
            }
        }
        if (6*searchPage+2 < Controller.getController().searchResults.size()) {
            searchResultPanel3.setResultTitle(
                    Controller.getController().searchResults.get(6*searchPage+2).name);
            if (Client.client.getGameInfo(searchList.get(6*searchPage+2).appid) != null){
            searchResultPanel3.setResultImage(
                    new URL(Client.client.getGameInfo(
                            searchList.get(6*searchPage+2).appid).data.header_image));
            }
        }
        if (6*searchPage+3 < Controller.getController().searchResults.size()) {
            searchResultPanel4.setResultTitle(
                    Controller.getController().searchResults.get(6*searchPage+3).name);
            if (Client.client.getGameInfo(searchList.get(6*searchPage+3).appid) != null){
            searchResultPanel4.setResultImage(
                    new URL(Client.client.getGameInfo(
                            searchList.get(6*searchPage+3).appid).data.header_image));
            }
        }
        if (6*searchPage+4 < Controller.getController().searchResults.size()) {
            searchResultPanel5.setResultTitle(
                    Controller.getController().searchResults.get(6*searchPage+4).name);
            if (Client.client.getGameInfo(searchList.get(6*searchPage+4).appid) != null){
            searchResultPanel5.setResultImage(
                    new URL(Client.client.getGameInfo(
                            searchList.get(6*searchPage+4).appid).data.header_image));
            }
        }
        if (6*searchPage+5 < Controller.getController().searchResults.size()) {
            searchResultPanel6.setResultTitle(
                    Controller.getController().searchResults.get(6*searchPage+5).name);
            if (Client.client.getGameInfo(searchList.get(6*searchPage+5).appid) != null){
            searchResultPanel6.setResultImage(
                    new URL(Client.client.getGameInfo(
                            searchList.get(6*searchPage+5).appid).data.header_image));
            }
        }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoLeft;
    private javax.swing.JButton btnGoRight;
    private edu.endicott.csc.forms.SearchResultPanel searchResultPanel1;
    private edu.endicott.csc.forms.SearchResultPanel searchResultPanel2;
    private edu.endicott.csc.forms.SearchResultPanel searchResultPanel3;
    private edu.endicott.csc.forms.SearchResultPanel searchResultPanel4;
    private edu.endicott.csc.forms.SearchResultPanel searchResultPanel5;
    private edu.endicott.csc.forms.SearchResultPanel searchResultPanel6;
    private edu.endicott.csc.forms.SideBar sideBar1;
    private edu.endicott.csc.forms.TopOptionsBar topOptionsBar1;
    // End of variables declaration//GEN-END:variables
}
