/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.endicott.csc.Forms;

import edu.endicott.csc.finalproject.*;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author cesar
 */
public class EntryPanel extends javax.swing.JPanel {
    GameInfo gameInfo;
    
    /**
     * Creates new form EntryPanel
     */
    public EntryPanel() {
        // IMPORTANT TO-DO: Find a way to add the information of the current game
        // to the field gameInfo in the constructor
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEntryImage = new javax.swing.JLabel();
        lblEntryTitle = new javax.swing.JLabel();
        lblGenres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDeveloper = new javax.swing.JLabel();
        lblReleaseDate = new javax.swing.JLabel();
        lblPublisher = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();
        btnAddGame = new javax.swing.JButton();
        btnRemoveGame = new javax.swing.JButton();

        lblEntryImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntryImage.setText("IMAGE");

        lblEntryTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEntryTitle.setText("TITLE");

        lblGenres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGenres.setText("Genres");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(948, 154));
        jPanel3.setMinimumSize(new java.awt.Dimension(948, 154));

        lblDeveloper.setText("Developer: ");

        lblReleaseDate.setText("Release Date: ");

        lblPublisher.setText("Publisher: ");

        lblWebsite.setText("Website: ");
        lblWebsite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWebsiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblWebsiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblWebsiteMouseExited(evt);
            }
        });

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtaDescription.setEditable(false);
        jtaDescription.setColumns(20);
        jtaDescription.setLineWrap(true);
        jtaDescription.setRows(5);
        jtaDescription.setText("Description: ");
        jtaDescription.setWrapStyleWord(true);
        jtaDescription.setMaximumSize(new java.awt.Dimension(164, 74));
        jScrollPane1.setViewportView(jtaDescription);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReleaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDeveloper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnAddGame.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddGame.setText("Add Game");
        btnAddGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddGameMouseClicked(evt);
            }
        });
        btnAddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGameActionPerformed(evt);
            }
        });

        btnRemoveGame.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRemoveGame.setText("Remove");
        btnRemoveGame.setEnabled(false);
        btnRemoveGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveGameMouseClicked(evt);
            }
        });
        btnRemoveGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEntryImage, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEntryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(210, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAddGame, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemoveGame, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(273, 273, 273))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEntryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnAddGame)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveGame))
                    .addComponent(lblEntryImage, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(602, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateInformation() {
        try {
            URL url = new URL(gameInfo.data.header_image);
            BufferedImage buffImage = ImageIO.read(url);
            ImageIcon icon = new ImageIcon(buffImage);
            
            lblEntryImage.setIcon(icon);

        } catch (MalformedURLException ex) {
            Logger.getLogger(EntryPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EntryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        lblEntryTitle.setText(gameInfo.data.name);
        
        String genresString = "";
        if (gameInfo.data.genres != null) {
            for (int i=0; i < gameInfo.data.genres.size(); i++) {
                genresString = genresString + gameInfo.data.genres.get(i).description;
                if (gameInfo.data.genres.size() > 1 && i < gameInfo.data.genres.size() - 1) {
                    genresString = genresString + ", ";
                }
            }
        }
        lblGenres.setText(genresString);
        
        jtaDescription.setText("Description:\n" + gameInfo.data.short_description);
        lblReleaseDate.setText("Release date: " + gameInfo.data.release_date);
        
        String publishersString = "Publishers: ";
        if (gameInfo.data.publishers != null) {
            for (int i=0; i < gameInfo.data.publishers.size(); i++) {
                publishersString = publishersString + gameInfo.data.publishers.get(i);
                if (gameInfo.data.publishers.size() > 1 && i < gameInfo.data.publishers.size() - 1) {
                    publishersString = publishersString + ", ";
                }
            }
        }
        lblPublisher.setText(publishersString);
        
        String developersString = "Developers: ";
        if (gameInfo.data.developers != null) {
            for (int i=0; i < gameInfo.data.developers.size(); i++) {
                developersString = developersString + gameInfo.data.developers.get(i);
                if (gameInfo.data.developers.size() > 1 && i < gameInfo.data.developers.size() - 1) {
                    developersString = developersString + ", ";
                }
            }
        }
        lblDeveloper.setText(developersString);
        
        lblWebsite.setText("Website: " + gameInfo.data.website);
        
        if (gameInfo.data.website == null) {
//            lblWebsite.setVisible(false);
            lblWebsite.setEnabled(false);
            lblWebsite.setText("");
        }
        else {
            lblWebsite.setVisible(true);
            lblWebsite.setEnabled(true);
        }
        
        btnAddGame.setEnabled(!Controller.getController().user.gameids.contains(Controller.getController().currentGameID));
        btnRemoveGame.setEnabled(Controller.getController().user.gameids.contains(Controller.getController().currentGameID));
    }
    
    private void btnAddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGameActionPerformed

    private void lblWebsiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWebsiteMouseClicked
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            try {
                Desktop.getDesktop().browse(new URI(gameInfo.data.website));
            } catch (IOException ex) {
                Logger.getLogger(EntryPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (URISyntaxException ex) {
                Logger.getLogger(EntryPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblWebsiteMouseClicked

    private void lblWebsiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWebsiteMouseEntered
        lblWebsite.setForeground(new Color(150, 150, 255));
    }//GEN-LAST:event_lblWebsiteMouseEntered

    private void lblWebsiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWebsiteMouseExited
        lblWebsite.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_lblWebsiteMouseExited

    private void btnAddGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddGameMouseClicked
        Controller.getController().addUserGameEntry(Controller.getController().currentGameID);
        
        btnAddGame.setEnabled(!Controller.getController().user.gameids.contains(Controller.getController().currentGameID));
        btnRemoveGame.setEnabled(Controller.getController().user.gameids.contains(Controller.getController().currentGameID));
    }//GEN-LAST:event_btnAddGameMouseClicked

    private void btnRemoveGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveGameMouseClicked
        Controller.getController().removeUserGameEntry(Controller.getController().currentGameID);
        
        btnAddGame.setEnabled(!Controller.getController().user.gameids.contains(Controller.getController().currentGameID));
        btnRemoveGame.setEnabled(Controller.getController().user.gameids.contains(Controller.getController().currentGameID));
    }//GEN-LAST:event_btnRemoveGameMouseClicked

    private void btnRemoveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveGameActionPerformed
        
    }//GEN-LAST:event_btnRemoveGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGame;
    private javax.swing.JButton btnRemoveGame;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaDescription;
    private javax.swing.JLabel lblDeveloper;
    private javax.swing.JLabel lblEntryImage;
    private javax.swing.JLabel lblEntryTitle;
    private javax.swing.JLabel lblGenres;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblReleaseDate;
    private javax.swing.JLabel lblWebsite;
    // End of variables declaration//GEN-END:variables
}
