/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.endicott.csc.forms;

import edu.endicott.csc.client.Client;
import edu.endicott.csc.finalproject.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cesar
 */
public class SideBar extends javax.swing.JPanel {
    private Controller controller;
    
    /**
     * Creates new form SideBar
     */
    public SideBar() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfSearch = new javax.swing.JTextField();
        lblSideButtonRandom = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jtfSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfSearch.setForeground(new java.awt.Color(153, 153, 153));
        jtfSearch.setText("Search:");
        jtfSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfSearchFocusLost(evt);
            }
        });
        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSearchKeyPressed(evt);
            }
        });

        lblSideButtonRandom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSideButtonRandom.setForeground(new java.awt.Color(255, 255, 255));
        lblSideButtonRandom.setText("Random Game");
        lblSideButtonRandom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSideButtonRandomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSideButtonRandomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSideButtonRandomMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(lblSideButtonRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblSideButtonRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(854, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cleanSearchBar() {
        jtfSearch.setText("Search:");
        jtfSearch.setForeground(new Color(153, 153, 153));
    }
    
    private void jtfSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSearchFocusGained
        if(jtfSearch.getText().equals("Search:")) {
            jtfSearch.setText("");
            jtfSearch.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_jtfSearchFocusGained

    private void jtfSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSearchFocusLost
        if(jtfSearch.getText().equals("")) {
            jtfSearch.setText("Search:");
            jtfSearch.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jtfSearchFocusLost

    private void jtfSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER) && (!jtfSearch.getText().equals(""))) {
            try {
                Controller.getController().searchResults = Client.client.getSearchList(jtfSearch.getText());
                Controller.getController().windows.get(Controller.getController().currentWindow).goToPage(Controller.SEARCH_WINDOW);
            } catch (IOException ex) {
                Logger.getLogger(SideBar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jtfSearchKeyPressed

    private void lblSideButtonRandomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSideButtonRandomMouseClicked
        try {
            Controller.getController().currentGameInfo = 
                        Client.client.getRandomGame();
            while (Controller.getController().currentGameInfo == null) {
                Controller.getController().currentGameInfo = 
                        Client.client.getRandomGame();
            }
                
            System.out.println(Controller.getController().currentGameInfo.data.name);
            
            Controller.getController()
                    .windows.get(Controller.getController().currentWindow)
                    .goToPage(Controller.ENTRY_WINDOW);
        } catch (IOException ex) {
            Logger.getLogger(SideBar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSideButtonRandomMouseClicked

    private void lblSideButtonRandomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSideButtonRandomMouseEntered
        lblSideButtonRandom.setForeground(new Color(0, 255, 255));
    }//GEN-LAST:event_lblSideButtonRandomMouseEntered

    private void lblSideButtonRandomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSideButtonRandomMouseExited
        lblSideButtonRandom.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_lblSideButtonRandomMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JLabel lblSideButtonRandom;
    // End of variables declaration//GEN-END:variables
}
