/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.endicott.csc.Forms;

import edu.endicott.csc.finalproject.*;
import java.awt.Color;

/**
 *
 * @author cesar
 */
public class SliderDisplay extends javax.swing.JPanel {
    private Controller controller;

    /**
     * Creates new form SliderDisplay
     */
    public SliderDisplay() {
        initComponents();
    }

    public void setTitle(String title) {
        lblTitle.setText(title);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblElement1 = new javax.swing.JLabel();
        lblElement2 = new javax.swing.JLabel();
        lblElement3 = new javax.swing.JLabel();
        lblElement4 = new javax.swing.JLabel();
        lblElement5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 51, 204));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setText("Title");

        lblElement1.setText("jLabel1");
        lblElement1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElement1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblElement1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblElement1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblElement1MouseExited(evt);
            }
        });

        lblElement2.setText("jLabel2");
        lblElement2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElement2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblElement2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblElement2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblElement2MouseExited(evt);
            }
        });

        lblElement3.setText("jLabel3");
        lblElement3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblElement4.setText("jLabel4");
        lblElement4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblElement5.setText("jLabel5");
        lblElement5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(lblElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(lblElement3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(lblElement4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(lblElement5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblElement5, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(lblElement4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblElement3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblElement2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblElement1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblElement1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElement1MouseClicked
//        Controller.getController().goToPage(Controller.ENTRY_WINDOW);
    }//GEN-LAST:event_lblElement1MouseClicked

    private void lblElement1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElement1MouseEntered
        lblElement1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblElement1MouseEntered

    private void lblElement1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElement1MouseExited
        lblElement1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblElement1MouseExited

    private void lblElement2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElement2MouseClicked
//        Controller.getController().goToPage(Controller.ENTRY_WINDOW);
    }//GEN-LAST:event_lblElement2MouseClicked

    private void lblElement2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElement2MouseEntered
        lblElement2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblElement2MouseEntered

    private void lblElement2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElement2MouseExited
        lblElement2.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblElement2MouseExited

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblElement1;
    private javax.swing.JLabel lblElement2;
    private javax.swing.JLabel lblElement3;
    private javax.swing.JLabel lblElement4;
    private javax.swing.JLabel lblElement5;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
