/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.endicott.csc.forms;

import edu.endicott.csc.client.Client;
import edu.endicott.csc.finalproject.*;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class TopOptionsBar extends javax.swing.JPanel {
    
    /**
     * Creates new form TopOptionsBar
     */
    public TopOptionsBar() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblGoHome = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("USERNAME");
        lblUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblUserName.setMaximumSize(new java.awt.Dimension(1000, 22));
        lblUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserNameMouseExited(evt);
            }
        });

        lblGoHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoHome.setText("HOME");
        lblGoHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblGoHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGoHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGoHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGoHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1658, Short.MAX_VALUE)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGoHome, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     *
     */
    public void setUsername() {
        lblUserName.setText(Controller.getController().username);
    }
    
    private void lblGoHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoHomeMouseEntered
        lblGoHome.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblGoHomeMouseEntered

    private void lblGoHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoHomeMouseExited
        lblGoHome.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblGoHomeMouseExited

    private void lblGoHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoHomeMouseClicked
        Controller.getController().windows.get(
                Controller.getController().currentWindow)
                .goToPage(Controller.MAIN_WINDOW);
    }//GEN-LAST:event_lblGoHomeMouseClicked

    private void lblUserNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserNameMouseEntered
        lblUserName.setForeground(new Color(10, 10, 255));
    }//GEN-LAST:event_lblUserNameMouseEntered

    private void lblUserNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserNameMouseExited
        lblUserName.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblUserNameMouseExited

    private void lblUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserNameMouseClicked
        if(!Controller.getController().user.gamelist.isEmpty()) {
            try {
                Controller.getController().searchResults =
                        Client.client.getUserList(Controller.getController().user.username);
            } catch (IOException ex) {
                Logger.getLogger(TopOptionsBar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Controller.getController()
                    .windows.get(Controller.getController().currentWindow)
                    .goToPage(Controller.SEARCH_WINDOW);
        }
        else {
            JOptionPane.showMessageDialog(this, "You stilll have no games in "
                    + "your collection!.", "ATTENTION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblUserNameMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblGoHome;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables
}
