/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.endicott.csc.Forms;

import edu.endicott.csc.finalproject.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class TopOptionsBar extends javax.swing.JPanel {
    
    /**
     * Creates new form TopOptionsBar
     */
    public TopOptionsBar() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblBackText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("USERNAME");
        lblUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblUserName.setMaximumSize(new java.awt.Dimension(1000, 22));
        lblUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserNameMouseExited(evt);
            }
        });

        lblBackText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackText.setText("BACK");
        lblBackText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBackText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBackText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1658, Short.MAX_VALUE)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBackText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setUsername() {
        lblUserName.setText(Controller.getController().username);
    }
    
    private void lblBackTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackTextMouseEntered
        lblBackText.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblBackTextMouseEntered

    private void lblBackTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackTextMouseExited
        lblBackText.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblBackTextMouseExited

    private void lblBackTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackTextMouseClicked
        Controller.getController().windows.get(
                Controller.getController().currentWindow).goToPreviousPage();
    }//GEN-LAST:event_lblBackTextMouseClicked

    private void lblUserNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserNameMouseEntered
        lblUserName.setForeground(new Color(10, 10, 255));
    }//GEN-LAST:event_lblUserNameMouseEntered

    private void lblUserNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserNameMouseExited
        lblUserName.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblUserNameMouseExited

    private void lblUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserNameMouseClicked
        if(Controller.getController().user.gameids.size() != 0) {
//            Controller.getController().searchWindow.displayUserGames();
//            Controller.getController().goToPage(Controller.SEARCH_WINDOW);
//            Controller.getController().searchWindow.setTitleLabel("Your Collection:");
        }
        else {
            JOptionPane.showMessageDialog(this, "You stilll have no games in "
                    + "your collection!.", "ATTENTION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblUserNameMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackText;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables
}
